/**
 * AUTHOR:AbnerMing
 * DATE:2024/5/28
 * INTRODUCE:刷新头，三个点属性
 * */
export declare class HeaderPointsAttr {
    isTextHide?: boolean;
    fontSize?: number | string | Resource;
    fontColor?: ResourceColor;
    animationMarginBottom?: Length;
    firstCircleColor?: ResourceColor;
    secondCircleColor?: ResourceColor;
    thirdCircleColor?: ResourceColor;
    circleWidth?: string | number;
    circleHeight?: string | number;
    circleSpacing?: Length;
    isAnimation?: boolean;
    secondFloorStatusText?: string;
    secondFloorStatusFontSize?: number | string | Resource;
    secondFloorStatusFontColor?: ResourceColor;
    secondFloorStatusFontWeight?: number | FontWeight | string;
    secondFloorStatusMarginBottom?: Length;
}
